webClientProfile:
  default:
    max-timeout: 10000
retryProfile:
  default:
    maxAttempt: 5
    backOffMaxInterval: 5000
    backOffInitialInterval: 200
    backOffMultiplier: 2
dataFlowAPIExecutor:
  jwtToken:
    api-url: http://localhost:3000/jwttoken/
    http-method: POST
    request-payload-transformer: jwtTokenRequest
  fico:
    api-url: http://localhost:3000/fico/
    http-method: POST
    request-header-mappers: jwt,cerdos-id
    pre-executor: jwtTokenAPIExecutor
    pre-executor-override: false
    pre-executor-transformer-class: ficoRequestTransformer
    post-executor: decisionResponseDBExecutor
    post-executor-override: false
    post-executor-transformer-class: ficoResponseForDSOR
dataFlowPayloadTransformer:
  jwtTokenRequest:
    template-spec: /jwt-request.json
    replace-fixed:
      - clientid,'wrwfdcwqcwqewqcewqc'
      - secret,'32432c23h8e23he23gc2378er2342378cg32487324c32874c32784ct32478c378'
  decisionRequestEntityCreator:
    expression-spec: "new com.lbg.rsk.cdp.demo.integration.crddec.entity.DecisionRequestEntity()"
    replace-with:
      - crdRqsId,headers.cerdos-id
      - applicationCustomerId,payload.applicationCustomerId
      - strategyType,payload.strategyType
      - channelType,payload.channelType
      - customerSegmentType,payload.customerSegmentType
      - dbRequestType,payload.dbRequestType
    replace-with-type:
      - payload,payload.payload,"new com.fasterxml.jackson.databind.ObjectMapper().writeValueAsString(#object)"
dataFlowDBExecutor:
  decisionResponseInDSOR:
    entity-class: DecisionResponseEntity
  decisionRequestInDSOR:
    entity-class: DecisionRequestEntity
    request-payload-transformer: decisionRequestEntityCreator
dataFlowDataGatherer:
  crddecgatherer:
    template-spec: /fico-bom-spec.json
    template-placeholders:
      - /{},fico,{}