dataFlowAPIExecutor:
  weather:
    api-url: ${weather-api-url}
    request-header-mappers: Content-Type
    uri-variables:
      name:
        - LAT
        - LONG
      expression:
       - "#jsonPath(payload, '$.lat').asText()"
       - "#jsonPath(payload, '$.long').asText()"
    response-spec: /weather-response-spec.json