webClientProfile:
  default:
    max-timeout: 10000
retryProfile:
  default:
    maxAttempt: 5
    backOffMaxInterval: 5000
    backOffInitialInterval: 200
    backOffMultiplier: 2
dataFlowAPIExecutor:
  soe:
    api-url: http://localhost:3000/bdcs/{ID}
    uri-variables:
      name:
        - ID
      expression:
        - "#jsonPath(payload, '$').asText()"
  ncino:
    api-url: http://localhost:3000/ncino/
    http-method: POST
    #response-spec: /remove-empty-spec.json
    response-payload-transformer: removeEmptyNode
dataFlowSpecExecutor:
  initialBOMPreparation:
    spec: /input.json
dataFlowDataGatherer:
  smeRenewal:
    template-spec: /fico-bom-spec.json
    template-transformers: decisionRequestData,soeIntoNCino,nCinoDataIntoInputData,populateCerdosID,cerdosIDInResponse
    template-placeholders:
      - /{},decisionRequestData,{}
dataFlowDataTransformer:
  cerdosIDInResponse:
    data-spec: decisionRequestData,populateCerdosID
    replace-with:
      - request.OrchestrationRequestId,value
  populateCerdosID:
    in-application: true
    bean-name: populateCerdosID
  decisionRequestData:
    data-spec: /fico-bom-spec.json,/defaults.yml
    replace-with:
      - request.DecisionRequest,DecisionRequest
      - request.OrchestrationServiceParameters,OrchestrationServiceParameters
    map-with:
      - request.DecisionRequest,DecisionServiceParameters,DecisionServiceParameters
  soeIntoNCino:
    data-spec: ncino,soe
    map-with:
      - Members.[0],soe.[0],CustomerBehaviours
    map-with-math:
      - Members.[*].partyID,soe.[*].applicationID,Members.[*],SOE[*],CustomerBehaviours
    replace-with:
      - Members.[*].LegalEntityID,soe.[*].ApplicationCustomerID
    replace-fixed:
      - Members.[*].ApplicationSICCode,"new java.lang.String('123')"
  nCinoDataIntoInputData:
    data-spec: decisionRequestData,ncino
    map-with:
      - request.DecisionRequest,{},InputData
dataFlowPayloadTransformer:
  removeEmptyNode:
    replace-with-type:
      - Members.[*].Party,soe,"#removeEmptyNodes(#object)"

